/**
 * Mock Data per sviluppo e preview
 * Dati realistici per testare l'UI senza backend
 */

export const mockArticles = [
  // Wellbeing
  {
    id: 1,
    title: '10 Abitudini Mattutine per Iniziare la Giornata con Energia',
    slug: '10-abitudini-mattutine-energia',
    category: 'Wellbeing',
    content: 'Iniziare la giornata nel modo giusto può fare la differenza tra una giornata produttiva e una noiosa. Scopri come creare una routine mattutina che ti carichi di energia positiva e ti prepari al meglio per affrontare le sfide quotidiane. Dalla meditazione al movimento, passando per una colazione nutriente, ogni piccolo gesto conta.',
    seoMetaTitle: 'Abitudini Mattutine: Come Iniziare la Giornata con Energia',
    seoMetaDescription: 'Scopri 10 abitudini mattutine scientificamente provate per aumentare energia, produttività e benessere generale.',
    featuredImageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&h=600&fit=crop',
    views: 1245,
    publishedAt: '2024-12-10T10:00:00Z',
    productIds: [1, 2],
  },
  {
    id: 2,
    title: 'Meditazione Mindfulness: Guida Completa per Principianti',
    slug: 'meditazione-mindfulness-guida-principianti',
    category: 'Wellbeing',
    content: 'La meditazione mindfulness è una pratica antica che ha trovato conferma scientifica nella medicina moderna. Questa guida completa ti accompagnerà passo dopo passo nel mondo della consapevolezza, insegnandoti tecniche semplici ma efficaci per ridurre lo stress, migliorare la concentrazione e aumentare il benessere generale.',
    seoMetaTitle: 'Meditazione Mindfulness: Guida Completa per Principianti',
    seoMetaDescription: 'Impara le basi della meditazione mindfulness con questa guida pratica. Tecniche, benefici e consigli per iniziare oggi stesso.',
    featuredImageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    views: 892,
    publishedAt: '2024-12-08T14:30:00Z',
    productIds: [3],
  },
  {
    id: 3,
    title: 'Sonno di Qualità: Come Dormire Meglio e Svegliarsi Riposati',
    slug: 'sonno-qualita-dormire-meglio',
    category: 'Wellbeing',
    content: 'Il sonno è fondamentale per la salute fisica e mentale. Scopri come ottimizzare la tua routine notturna, creare l\'ambiente ideale per dormire e adottare abitudini che migliorino la qualità del riposo. Dalla temperatura della stanza agli integratori naturali, tutto quello che serve per svegliarsi pieni di energia.',
    seoMetaTitle: 'Sonno di Qualità: Guida Completa per Dormire Meglio',
    seoMetaDescription: 'Migliora la qualità del tuo sonno con questi consigli scientifici. Ambiente, routine e prodotti per dormire meglio e svegliarsi riposati.',
    featuredImageUrl: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=800&h=600&fit=crop',
    views: 1567,
    publishedAt: '2024-12-05T09:15:00Z',
    productIds: [4, 5],
  },
  // Nutrition
  {
    id: 4,
    title: 'Superfood: I 15 Alimenti Più Nutrienti da Inserire nella Dieta',
    slug: 'superfood-15-alimenti-piu-nutrienti',
    category: 'Nutrition',
    content: 'I superfood sono alimenti ricchi di nutrienti essenziali che possono potenziare la tua salute. Dalle bacche di goji ai semi di chia, passando per il matcha e la spirulina, scopri quali alimenti offrono il massimo beneficio nutrizionale e come integrarli facilmente nella tua alimentazione quotidiana.',
    seoMetaTitle: 'Superfood: I 15 Alimenti Più Nutrienti per la Tua Salute',
    seoMetaDescription: 'Scopri i superfood più potenti e come integrarli nella tua dieta. Benefici, proprietà e ricette per massimizzare l\'assunzione di nutrienti.',
    featuredImageUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&h=600&fit=crop',
    views: 2103,
    publishedAt: '2024-12-12T11:20:00Z',
    productIds: [6, 7],
  },
  {
    id: 5,
    title: 'Integratori Proteici: Guida alla Scelta e all\'Uso Corretto',
    slug: 'integratori-proteici-guida-scelta',
    category: 'Nutrition',
    content: 'Le proteine sono essenziali per la costruzione muscolare, il recupero e la salute generale. Questa guida ti aiuterà a capire quando e come utilizzare gli integratori proteici, quali tipi scegliere in base alle tue esigenze e come integrarli correttamente nella tua alimentazione senza eccessi.',
    seoMetaTitle: 'Integratori Proteici: Guida Completa alla Scelta',
    seoMetaDescription: 'Tutto quello che devi sapere sugli integratori proteici: tipi, dosaggi, timing e come scegliere il prodotto giusto per le tue esigenze.',
    featuredImageUrl: 'https://images.unsplash.com/photo-1574680178050-55c6a6a96e0a?w=800&h=600&fit=crop',
    views: 1789,
    publishedAt: '2024-12-09T16:45:00Z',
    productIds: [8, 9],
  },
  {
    id: 6,
    title: 'Digestione Perfetta: Alimenti e Integratori per un Intestino Sano',
    slug: 'digestione-perfetta-intestino-sano',
    category: 'Nutrition',
    content: 'Un intestino sano è la base del benessere generale. Scopri quali alimenti favoriscono una digestione ottimale, quali probiotici e prebiotici possono aiutare e come mantenere l\'equilibrio del microbioma intestinale per migliorare energia, umore e salute complessiva.',
    seoMetaTitle: 'Digestione Perfetta: Guida per un Intestino Sano',
    seoMetaDescription: 'Migliora la tua digestione con alimenti e integratori specifici. Consigli pratici per un intestino sano e un benessere ottimale.',
    featuredImageUrl: 'https://images.unsplash.com/photo-1556910096-6f5e72db6803?w=800&h=600&fit=crop',
    views: 1345,
    publishedAt: '2024-12-07T13:10:00Z',
    productIds: [10],
  },
  // Fitness
  {
    id: 7,
    title: 'Home Workout: Allenamento Completo Senza Attrezzi',
    slug: 'home-workout-allenamento-senza-attrezzi',
    category: 'Fitness',
    content: 'Non serve una palestra per mantenersi in forma. Questo programma di home workout ti permetterà di allenare tutto il corpo usando solo il peso corporeo. Esercizi progressivi, routine settimanali e consigli per massimizzare i risultati anche in spazi ridotti.',
    seoMetaTitle: 'Home Workout: Allenamento Completo Senza Attrezzi',
    seoMetaDescription: 'Programma completo di home workout per allenare tutto il corpo. Esercizi, routine e consigli per risultati senza palestra.',
    featuredImageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=600&fit=crop',
    views: 2456,
    publishedAt: '2024-12-11T08:00:00Z',
    productIds: [11, 12],
  },
  {
    id: 8,
    title: 'Recupero Muscolare: Strategie per Ottimizzare il Recupero Post-Allenamento',
    slug: 'recupero-muscolare-strategie-post-allenamento',
    category: 'Fitness',
    content: 'Il recupero è tanto importante quanto l\'allenamento stesso. Impara le migliori strategie per ottimizzare il recupero muscolare: dalla nutrizione al sonno, passando per stretching, massaggi e integratori specifici. Massimizza i risultati dei tuoi allenamenti con un recupero intelligente.',
    seoMetaTitle: 'Recupero Muscolare: Guida Completa al Recupero Post-Allenamento',
    seoMetaDescription: 'Strategie scientifiche per ottimizzare il recupero muscolare. Nutrizione, sonno, stretching e integratori per risultati migliori.',
    featuredImageUrl: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&h=600&fit=crop',
    views: 1890,
    publishedAt: '2024-12-06T15:30:00Z',
    productIds: [13, 14],
  },
  {
    id: 9,
    title: 'HIIT Training: Allenamento ad Alta Intensità per Massimi Risultati',
    slug: 'hiit-training-alta-intensita',
    category: 'Fitness',
    content: 'L\'allenamento HIIT (High Intensity Interval Training) è uno dei metodi più efficaci per bruciare grassi e migliorare la condizione fisica in poco tempo. Scopri come strutturare sessioni HIIT efficaci, quali esercizi includere e come progredire gradualmente per evitare infortuni.',
    seoMetaTitle: 'HIIT Training: Guida all\'Allenamento ad Alta Intensità',
    seoMetaDescription: 'Tutto sull\'allenamento HIIT: benefici, struttura, esercizi e programmi per massimizzare risultati in poco tempo.',
    featuredImageUrl: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&h=600&fit=crop',
    views: 2234,
    publishedAt: '2024-12-04T10:45:00Z',
    productIds: [15],
  },
  // Mindset
  {
    id: 10,
    title: 'Growth Mindset: Come Sviluppare una Mentalità di Crescita',
    slug: 'growth-mindset-mentalita-crescita',
    category: 'Mindset',
    content: 'La mentalità di crescita è la chiave per superare limiti e raggiungere obiettivi ambiziosi. Impara a trasformare le sfide in opportunità, gli errori in apprendimento e le critiche in feedback costruttivo. Strategie pratiche per sviluppare un mindset che favorisce il successo personale e professionale.',
    seoMetaTitle: 'Growth Mindset: Come Sviluppare una Mentalità di Crescita',
    seoMetaDescription: 'Sviluppa una mentalità di crescita con queste strategie pratiche. Trasforma sfide e errori in opportunità di crescita personale.',
    featuredImageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=600&fit=crop',
    views: 1678,
    publishedAt: '2024-12-13T12:00:00Z',
    productIds: [16],
  },
  {
    id: 11,
    title: 'Gestione dello Stress: Tecniche Efficaci per Ridurre l\'Ansia',
    slug: 'gestione-stress-tecniche-ridurre-ansia',
    category: 'Mindset',
    content: 'Lo stress cronico può compromettere seriamente la qualità della vita. Scopri tecniche scientificamente provate per gestire lo stress e ridurre l\'ansia: dalla respirazione consapevole alle tecniche di visualizzazione, passando per integratori naturali e cambiamenti nello stile di vita.',
    seoMetaTitle: 'Gestione dello Stress: Tecniche per Ridurre Ansia e Tensioni',
    seoMetaDescription: 'Tecniche efficaci per gestire lo stress e ridurre l\'ansia. Metodi pratici e naturali per migliorare il benessere mentale.',
    featuredImageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&h=600&fit=crop',
    views: 1987,
    publishedAt: '2024-12-10T14:20:00Z',
    productIds: [17, 18],
  },
  {
    id: 12,
    title: 'Produttività Personale: Sistemi e Metodi per Essere Più Efficaci',
    slug: 'produttivita-personale-sistemi-metodi',
    category: 'Mindset',
    content: 'Essere produttivi non significa lavorare di più, ma lavorare meglio. Esplora sistemi collaudati come Getting Things Done, il metodo Pomodoro e la matrice di Eisenhower. Impara a gestire le priorità, eliminare le distrazioni e ottimizzare il tuo tempo per risultati migliori con meno sforzo.',
    seoMetaTitle: 'Produttività Personale: Sistemi per Essere Più Efficaci',
    seoMetaDescription: 'Sistemi e metodi collaudati per aumentare la produttività personale. Gestione del tempo, priorità e focus per risultati migliori.',
    featuredImageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=600&fit=crop',
    views: 1456,
    publishedAt: '2024-12-08T11:30:00Z',
    productIds: [19],
  },
  // Productivity
  {
    id: 13,
    title: 'Deep Work: Come Concentrarsi in un Mondo Distratto',
    slug: 'deep-work-concentrarsi-mondo-distratto',
    category: 'Productivity',
    content: 'Il deep work è la capacità di concentrarsi senza distrazioni su compiti cognitivamente impegnativi. In un\'epoca di notifiche continue e multitasking, questa abilità è diventata sempre più rara e preziosa. Scopri come creare le condizioni ideali per il deep work e aumentare drasticamente la qualità del tuo output.',
    seoMetaTitle: 'Deep Work: Come Sviluppare Concentrazione Profonda',
    seoMetaDescription: 'Impara l\'arte del deep work per aumentare concentrazione e produttività. Strategie pratiche per lavorare senza distrazioni.',
    featuredImageUrl: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800&h=600&fit=crop',
    views: 2134,
    publishedAt: '2024-12-14T09:15:00Z',
    productIds: [20],
  },
  {
    id: 14,
    title: 'Time Blocking: Il Metodo per Organizzare Ogni Giorno',
    slug: 'time-blocking-metodo-organizzare-giorno',
    category: 'Productivity',
    content: 'Il time blocking è un sistema di organizzazione del tempo che assegna blocchi specifici a ogni attività. Questo metodo ti aiuta a essere più realistico su quanto tempo richiedono le attività, riduce il multitasking e aumenta la produttività. Guida pratica per implementare il time blocking nella tua routine.',
    seoMetaTitle: 'Time Blocking: Metodo per Organizzare Ogni Giorno',
    seoMetaDescription: 'Impara il time blocking per organizzare meglio il tuo tempo. Sistema pratico per aumentare produttività e ridurre lo stress.',
    featuredImageUrl: 'https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=800&h=600&fit=crop',
    views: 1789,
    publishedAt: '2024-12-11T13:45:00Z',
    productIds: [21],
  },
  {
    id: 15,
    title: 'Digital Minimalism: Ridurre il Rumore Digitale per Focalizzarsi',
    slug: 'digital-minimalism-ridurre-rumore-digitale',
    category: 'Productivity',
    content: 'Il digital minimalism è una filosofia che promuove un uso intenzionale della tecnologia. Invece di essere costantemente connessi, impariamo a usare gli strumenti digitali in modo strategico per supportare i nostri valori e obiettivi. Scopri come ridurre il rumore digitale e riconquistare tempo e attenzione.',
    seoMetaTitle: 'Digital Minimalism: Ridurre il Rumore Digitale',
    seoMetaDescription: 'Adotta il digital minimalism per usare la tecnologia in modo intenzionale. Riduci distrazioni e riconquista tempo e focus.',
    featuredImageUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&h=600&fit=crop',
    views: 1654,
    publishedAt: '2024-12-09T10:20:00Z',
    productIds: [22],
  },
  // Wealth
  {
    id: 16,
    title: 'Investimenti per Principianti: Guida Completa per Iniziare',
    slug: 'investimenti-principianti-guida-completa',
    category: 'Wealth',
    content: 'Iniziare a investire può sembrare intimidatorio, ma con le basi giuste è accessibile a tutti. Questa guida completa ti accompagnerà nei primi passi: dai concetti fondamentali alla scelta delle piattaforme, passando per strategie di diversificazione e gestione del rischio. Costruisci ricchezza nel tempo con un approccio consapevole.',
    seoMetaTitle: 'Investimenti per Principianti: Guida Completa per Iniziare',
    seoMetaDescription: 'Guida completa agli investimenti per principianti. Concetti base, strategie e strumenti per iniziare a costruire ricchezza.',
    featuredImageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=600&fit=crop',
    views: 2890,
    publishedAt: '2024-12-15T08:30:00Z',
    productIds: [23],
  },
  {
    id: 17,
    title: 'FIRE Movement: Raggiungere l\'Indipendenza Finanziaria',
    slug: 'fire-movement-indipendenza-finanziaria',
    category: 'Wealth',
    content: 'Il movimento FIRE (Financial Independence, Retire Early) promuove l\'indipendenza finanziaria attraverso risparmio aggressivo e investimenti intelligenti. Scopri i principi del FIRE, come calcolare il tuo "FIRE number", strategie di risparmio e investimento, e come bilanciare il presente con il futuro finanziario.',
    seoMetaTitle: 'FIRE Movement: Come Raggiungere l\'Indipendenza Finanziaria',
    seoMetaDescription: 'Scopri il movimento FIRE e come raggiungere l\'indipendenza finanziaria. Strategie pratiche per risparmiare e investire intelligentemente.',
    featuredImageUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=600&fit=crop',
    views: 2345,
    publishedAt: '2024-12-12T15:00:00Z',
    productIds: [24],
  },
  {
    id: 18,
    title: 'Side Hustle: Come Creare Entrate Aggiuntive Online',
    slug: 'side-hustle-creare-entrate-aggiuntive-online',
    category: 'Wealth',
    content: 'Un side hustle può essere il primo passo verso l\'indipendenza finanziaria o semplicemente un modo per aumentare le entrate. Esplora diverse opportunità di guadagno online: dal freelancing alla creazione di contenuti, passando per e-commerce e affiliazioni. Guida pratica per iniziare il tuo side hustle oggi.',
    seoMetaTitle: 'Side Hustle: Come Creare Entrate Aggiuntive Online',
    seoMetaDescription: 'Scopri come creare entrate aggiuntive online con un side hustle. Opportunità, strategie e consigli per iniziare subito.',
    featuredImageUrl: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=800&h=600&fit=crop',
    views: 3124,
    publishedAt: '2024-12-10T16:15:00Z',
    productIds: [25],
  },
  // Wellbeing Sessuale
  {
    id: 19,
    title: 'Benessere Sessuale: Guida Completa alla Vitalità e Intimità',
    slug: 'benessere-sessuale-guida-vitalita-intimita',
    category: 'Wellbeing',
    content: 'Il benessere sessuale è una componente fondamentale della salute generale e della qualità della vita. Scopri come migliorare la tua vitalità sessuale attraverso nutrizione, esercizio, gestione dello stress e comunicazione. Una guida completa per uomini e donne che vogliono ottimizzare la propria intimità e soddisfazione.',
    seoMetaTitle: 'Benessere Sessuale: Guida Completa alla Vitalità e Intimità',
    seoMetaDescription: 'Scopri come migliorare il tuo benessere sessuale attraverso nutrizione, esercizio e comunicazione. Guida completa per vitalità e intimità ottimali.',
    featuredImageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&h=600&fit=crop',
    views: 4567,
    publishedAt: '2024-12-16T10:00:00Z',
    productIds: [26, 27, 28],
  },
  {
    id: 20,
    title: 'Integratori per il Vigore Sessuale: Cosa Funziona Davvero',
    slug: 'integratori-vigore-sessuale-cosa-funziona',
    category: 'Nutrition',
    content: 'Gli integratori per il vigore sessuale possono supportare la performance e la vitalità. Scopri quali ingredienti sono scientificamente provati, come lo zinco, la L-arginina, il ginseng e il maca. Guida completa ai dosaggi, timing e combinazioni efficaci per massimizzare i risultati.',
    seoMetaTitle: 'Integratori per il Vigore Sessuale: Guida Scientifica',
    seoMetaDescription: 'Scopri gli integratori scientificamente provati per migliorare il vigore sessuale. Ingredienti, dosaggi e combinazioni efficaci.',
    featuredImageUrl: 'https://images.unsplash.com/photo-1550572017-edd951b55104?w=800&h=600&fit=crop',
    views: 3890,
    publishedAt: '2024-12-14T14:30:00Z',
    productIds: [26, 27, 29],
  },
  {
    id: 21,
    title: 'Sessuologia Tantrica: Riscoprire l\'Intimità Profonda',
    slug: 'sessuologia-tantrica-intimita-profonda',
    category: 'Wellbeing',
    content: 'La sessuologia tantrica offre un approccio olistico all\'intimità, combinando tecniche antiche con conoscenze moderne. Impara come migliorare la connessione con il partner, aumentare la consapevolezza del corpo e trasformare l\'esperienza sessuale in un percorso di crescita personale e spirituale.',
    seoMetaTitle: 'Sessuologia Tantrica: Riscoprire l\'Intimità Profonda',
    seoMetaDescription: 'Scopri la sessuologia tantrica per migliorare l\'intimità e la connessione con il partner. Tecniche antiche per una vita sessuale più soddisfacente.',
    featuredImageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    views: 3123,
    publishedAt: '2024-12-13T11:20:00Z',
    productIds: [30, 31],
  },
  {
    id: 22,
    title: 'Benessere Sessuale Femminile: Energia, Desiderio e Soddisfazione',
    slug: 'benessere-sessuale-femminile-energia-desiderio',
    category: 'Wellbeing',
    content: 'Il benessere sessuale femminile è influenzato da molti fattori: ormoni, stress, nutrizione e benessere mentale. Scopri come supportare il desiderio, migliorare la lubrificazione naturale, aumentare l\'energia e raggiungere una soddisfazione più profonda attraverso un approccio integrato.',
    seoMetaTitle: 'Benessere Sessuale Femminile: Energia, Desiderio e Soddisfazione',
    seoMetaDescription: 'Guida completa al benessere sessuale femminile. Come supportare desiderio, energia e soddisfazione attraverso nutrizione e benessere.',
    featuredImageUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&h=600&fit=crop',
    views: 2789,
    publishedAt: '2024-12-12T09:45:00Z',
    productIds: [32, 33],
  },
  {
    id: 23,
    title: 'Performance Sessuale Maschile: Energia, Resistenza e Confidenza',
    slug: 'performance-sessuale-maschile-energia-resistenza',
    category: 'Wellbeing',
    content: 'La performance sessuale maschile dipende da energia fisica, salute cardiovascolare, livelli ormonali e benessere mentale. Scopri come migliorare resistenza, vigore e confidenza attraverso esercizio, nutrizione mirata, gestione dello stress e integratori specifici.',
    seoMetaTitle: 'Performance Sessuale Maschile: Energia, Resistenza e Confidenza',
    seoMetaDescription: 'Guida completa per migliorare la performance sessuale maschile. Energia, resistenza e confidenza attraverso esercizio e nutrizione.',
    featuredImageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=600&fit=crop',
    views: 4234,
    publishedAt: '2024-12-11T16:00:00Z',
    productIds: [26, 27, 34],
  },
  {
    id: 24,
    title: 'Comunicazione e Intimità: Costruire una Relazione Sessuale Soddisfacente',
    slug: 'comunicazione-intimita-relazione-sessuale',
    category: 'Mindset',
    content: 'Una comunicazione aperta e rispettosa è la base per un\'intimità sessuale soddisfacente. Impara tecniche per esprimere i tuoi desideri, ascoltare il partner e creare un ambiente di fiducia e apertura. Scopri come la comunicazione può trasformare la tua vita sessuale.',
    seoMetaTitle: 'Comunicazione e Intimità: Costruire una Relazione Sessuale Soddisfacente',
    seoMetaDescription: 'Scopri come migliorare la comunicazione per costruire un\'intimità sessuale più soddisfacente. Tecniche pratiche per coppie.',
    featuredImageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=600&fit=crop',
    views: 2345,
    publishedAt: '2024-12-10T13:30:00Z',
    productIds: [30, 35],
  },
  // Sostenibilità Ambientale
  {
    id: 25,
    title: 'Ridurre il Tuo Impatto Ambientale: Guida Pratica alla Sostenibilità',
    slug: 'ridurre-impatto-ambientale-guida-sostenibilita',
    category: 'Wellbeing',
    content: 'Ridurre il proprio impatto ambientale è una scelta consapevole che migliora sia il pianeta che il benessere personale. Scopri come iniziare: dall\'energia rinnovabile al fotovoltaico, passando per scelte quotidiane sostenibili. Una guida completa per vivere in modo più ecologico e rispettoso dell\'ambiente.',
    seoMetaTitle: 'Ridurre Impatto Ambientale: Guida Pratica alla Sostenibilità',
    seoMetaDescription: 'Scopri come ridurre il tuo impatto ambientale attraverso energia rinnovabile, fotovoltaico e scelte sostenibili. Guida completa alla sostenibilità.',
    featuredImageUrl: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&h=600&fit=crop',
    views: 3456,
    publishedAt: '2024-12-17T09:00:00Z',
    productIds: [36, 37, 38],
  },
  {
    id: 26,
    title: 'Fotovoltaico Domestico: Guida Completa all\'Installazione e Risparmio',
    slug: 'fotovoltaico-domestico-guida-installazione-risparmio',
    category: 'Wealth',
    content: 'Il fotovoltaico domestico è un investimento che riduce l\'impatto ambientale e le bollette. Scopri come funziona, quanto costa, quali sono gli incentivi disponibili e come scegliere il sistema giusto per la tua casa. Calcola il risparmio e l\'impatto positivo sull\'ambiente.',
    seoMetaTitle: 'Fotovoltaico Domestico: Guida Completa all\'Installazione',
    seoMetaDescription: 'Guida completa al fotovoltaico domestico: costi, incentivi, installazione e risparmio. Scopri come produrre energia pulita a casa tua.',
    featuredImageUrl: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&h=600&fit=crop',
    views: 4123,
    publishedAt: '2024-12-16T11:30:00Z',
    productIds: [36, 37, 39],
  },
  {
    id: 27,
    title: 'Sostenibilità Quotidiana: 50 Azioni per Vivere Più Green',
    slug: 'sostenibilita-quotidiana-50-azioni-green',
    category: 'Wellbeing',
    content: 'La sostenibilità inizia dalle piccole azioni quotidiane. Scopri 50 modi pratici per ridurre il tuo impatto ambientale: dalla riduzione dei rifiuti al risparmio energetico, passando per scelte di consumo consapevoli. Ogni gesto conta per un futuro più sostenibile.',
    seoMetaTitle: 'Sostenibilità Quotidiana: 50 Azioni per Vivere Più Green',
    seoMetaDescription: '50 azioni pratiche per vivere in modo più sostenibile. Riduci il tuo impatto ambientale con scelte quotidiane consapevoli.',
    featuredImageUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&h=600&fit=crop',
    views: 2890,
    publishedAt: '2024-12-15T14:20:00Z',
    productIds: [40, 41, 42],
  },
  {
    id: 28,
    title: 'Energia Rinnovabile: Investire nel Futuro Sostenibile',
    slug: 'energia-rinnovabile-investire-futuro-sostenibile',
    category: 'Wealth',
    content: 'L\'energia rinnovabile è il futuro. Scopri come investire in soluzioni sostenibili: fotovoltaico, eolico, pompe di calore. Una guida per ridurre l\'impatto ambientale e creare valore economico attraverso scelte energetiche intelligenti.',
    seoMetaTitle: 'Energia Rinnovabile: Investire nel Futuro Sostenibile',
    seoMetaDescription: 'Guida agli investimenti in energia rinnovabile. Fotovoltaico, eolico e soluzioni sostenibili per ridurre impatto ambientale e costi.',
    featuredImageUrl: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=800&h=600&fit=crop',
    views: 3678,
    publishedAt: '2024-12-14T10:15:00Z',
    productIds: [36, 37, 43],
  },
  {
    id: 29,
    title: 'Risparmio Energetico: Ridurre Consumi e Bollette',
    slug: 'risparmio-energetico-ridurre-consumi-bollette',
    category: 'Wealth',
    content: 'Risparmiare energia significa risparmiare denaro e proteggere l\'ambiente. Scopri strategie pratiche per ridurre i consumi domestici: isolamento termico, elettrodomestici efficienti, illuminazione LED, termostati intelligenti. Investimenti che si ripagano nel tempo.',
    seoMetaTitle: 'Risparmio Energetico: Ridurre Consumi e Bollette',
    seoMetaDescription: 'Strategie pratiche per risparmiare energia e ridurre le bollette. Isolamento, elettrodomestici efficienti e soluzioni smart home.',
    featuredImageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=600&fit=crop',
    views: 3124,
    publishedAt: '2024-12-13T16:00:00Z',
    productIds: [44, 45, 46],
  },
  {
    id: 30,
    title: 'Stile di Vita Sostenibile: Benessere Personale e Planetario',
    slug: 'stile-vita-sostenibile-benessere-personale-planetario',
    category: 'Wellbeing',
    content: 'Uno stile di vita sostenibile migliora sia il benessere personale che quello del pianeta. Scopri come allineare le tue scelte quotidiane con i tuoi valori ambientali: alimentazione consapevole, mobilità sostenibile, consumo responsabile. Un percorso verso un futuro migliore.',
    seoMetaTitle: 'Stile di Vita Sostenibile: Benessere Personale e Planetario',
    seoMetaDescription: 'Scopri come adottare uno stile di vita sostenibile che migliora benessere personale e ambientale. Guida pratica e consapevole.',
    featuredImageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&h=600&fit=crop',
    views: 2567,
    publishedAt: '2024-12-12T13:45:00Z',
    productIds: [40, 47, 48],
  },
];

export const mockProducts = [
  {
    id: 1,
    name: 'Integratore Multivitaminico Premium',
    category: 'Nutrition',
    description: 'Formula completa con 25 vitamine e minerali essenziali per supportare energia, immunità e benessere generale.',
    price: 29.99,
    affiliateLink: 'https://example.com/product/1',
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951b55104?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 5.5,
  },
  {
    id: 2,
    name: 'Tappetino Yoga Premium',
    category: 'Fitness',
    description: 'Tappetino antiscivolo ecologico, perfetto per yoga, pilates e meditazione. Spessore ottimale per comfort e stabilità.',
    price: 45.00,
    affiliateLink: 'https://example.com/product/2',
    imageUrl: 'https://images.unsplash.com/photo-1601925260368-ae2f83d8b5b9?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 6.0,
  },
  {
    id: 3,
    name: 'Cuscino Meditazione Memory Foam',
    category: 'Wellbeing',
    description: 'Cuscino ergonomico per meditazione e mindfulness. Supporto perfetto per la postura durante la pratica.',
    price: 39.99,
    affiliateLink: 'https://example.com/product/3',
    imageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 5.0,
  },
  {
    id: 4,
    name: 'Integratore Melatonina Naturale',
    category: 'Wellbeing',
    description: 'Melatonina pura per supportare il sonno naturale. Formula senza additivi, ideale per migliorare la qualità del riposo.',
    price: 19.99,
    affiliateLink: 'https://example.com/product/4',
    imageUrl: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 7.0,
  },
  {
    id: 5,
    name: 'Maschera Sonno in Seta',
    category: 'Wellbeing',
    description: 'Maschera per gli occhi in seta naturale, blocca completamente la luce per un sonno profondo e riposante.',
    price: 24.99,
    affiliateLink: 'https://example.com/product/5',
    imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 6.5,
  },
  {
    id: 6,
    name: 'Polvere Superfood Mix',
    category: 'Nutrition',
    description: 'Mix di superfood biologici: spirulina, matcha, bacche di goji e acai. Aggiungi energia e nutrienti ai tuoi smoothie.',
    price: 34.99,
    affiliateLink: 'https://example.com/product/6',
    imageUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 8.0,
  },
  {
    id: 7,
    name: 'Olio di Cocco Extra Vergine',
    category: 'Nutrition',
    description: 'Olio di cocco biologico spremuto a freddo. Perfetto per cucina, beauty routine e integrazione alimentare.',
    price: 16.99,
    affiliateLink: 'https://example.com/product/7',
    imageUrl: 'https://images.unsplash.com/photo-1609859904090-30f4c8462c0c?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 5.0,
  },
  {
    id: 8,
    name: 'Proteine Whey Isolate',
    category: 'Nutrition',
    description: 'Proteine del siero del latte isolate, 25g per porzione. Perfette per il recupero post-allenamento e la crescita muscolare.',
    price: 49.99,
    affiliateLink: 'https://example.com/product/8',
    imageUrl: 'https://images.unsplash.com/photo-1574680178050-55c6a6a96e0a?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 10.0,
  },
  {
    id: 9,
    name: 'Barrette Proteiche Naturali',
    category: 'Nutrition',
    description: 'Barrette proteiche con ingredienti naturali, senza zuccheri aggiunti. Snack perfetto per energia sostenuta.',
    price: 24.99,
    affiliateLink: 'https://example.com/product/9',
    imageUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 7.5,
  },
  {
    id: 10,
    name: 'Probiotici Multi-Ceppo',
    category: 'Nutrition',
    description: 'Integratore probiotico con 50 miliardi di CFU e 12 ceppi diversi. Supporta la salute digestiva e il sistema immunitario.',
    price: 32.99,
    affiliateLink: 'https://example.com/product/10',
    imageUrl: 'https://images.unsplash.com/photo-1556910096-6f5e72db6803?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 6.0,
  },
  {
    id: 11,
    name: 'Set Pesi Regolabili',
    category: 'Fitness',
    description: 'Set di pesi regolabili da 2.5kg a 20kg. Perfetto per home workout, risparmia spazio e denaro rispetto ai pesi tradizionali.',
    price: 89.99,
    affiliateLink: 'https://example.com/product/11',
    imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 8.5,
  },
  {
    id: 12,
    name: 'Resistance Bands Set',
    category: 'Fitness',
    description: 'Set completo di elastici fitness con 5 livelli di resistenza. Ideali per allenamento completo del corpo.',
    price: 19.99,
    affiliateLink: 'https://example.com/product/12',
    imageUrl: 'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 7.0,
  },
  {
    id: 13,
    name: 'Foam Roller Professionale',
    category: 'Fitness',
    description: 'Foam roller ad alta densità per massaggio miofasciale e recupero muscolare. Riduce tensioni e migliora flessibilità.',
    price: 29.99,
    affiliateLink: 'https://example.com/product/13',
    imageUrl: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 6.5,
  },
  {
    id: 14,
    name: 'Integratore BCAA',
    category: 'Fitness',
    description: 'Aminoacidi a catena ramificata per supportare il recupero muscolare e ridurre l\'affaticamento durante l\'allenamento.',
    price: 27.99,
    affiliateLink: 'https://example.com/product/14',
    imageUrl: 'https://images.unsplash.com/photo-1594736797933-d0cbc2a0c5e1?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 9.0,
  },
  {
    id: 15,
    name: 'Cronometro Interval Timer',
    category: 'Fitness',
    description: 'Timer professionale per allenamenti HIIT e Tabata. Display grande, facile da usare, resistente all\'acqua.',
    price: 24.99,
    affiliateLink: 'https://example.com/product/15',
    imageUrl: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 5.5,
  },
  {
    id: 16,
    name: 'Libro Growth Mindset',
    category: 'Mindset',
    description: 'Guida completa allo sviluppo di una mentalità di crescita. Strategie pratiche per superare limiti e raggiungere obiettivi.',
    price: 18.99,
    affiliateLink: 'https://example.com/product/16',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 4.5,
  },
  {
    id: 17,
    name: 'Diffusore Aromaterapia',
    category: 'Mindset',
    description: 'Diffusore ad ultrasuoni con luci LED. Perfetto per creare un ambiente rilassante con oli essenziali.',
    price: 39.99,
    affiliateLink: 'https://example.com/product/17',
    imageUrl: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 6.0,
  },
  {
    id: 18,
    name: 'Integratore Ashwagandha',
    category: 'Mindset',
    description: 'Ashwagandha pura per supportare la gestione dello stress e migliorare il benessere mentale. Adattogeno naturale.',
    price: 22.99,
    affiliateLink: 'https://example.com/product/18',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 7.5,
  },
  {
    id: 19,
    name: 'Notebook Produttività',
    category: 'Productivity',
    description: 'Taccuino per time blocking e pianificazione giornaliera. Layout ottimizzato per massimizzare la produttività.',
    price: 14.99,
    affiliateLink: 'https://example.com/product/19',
    imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 5.0,
  },
  {
    id: 20,
    name: 'Cuffie Noise Cancelling',
    category: 'Productivity',
    description: 'Cuffie con cancellazione attiva del rumore. Perfette per deep work e concentrazione in ambienti rumorosi.',
    price: 199.99,
    affiliateLink: 'https://example.com/product/20',
    imageUrl: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 8.0,
  },
  {
    id: 21,
    name: 'Pomodoro Timer Fisico',
    category: 'Productivity',
    description: 'Timer meccanico per il metodo Pomodoro. Design minimal, funziona senza batterie, perfetto per focus.',
    price: 12.99,
    affiliateLink: 'https://example.com/product/21',
    imageUrl: 'https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 4.0,
  },
  {
    id: 22,
    name: 'App Blocking Software',
    category: 'Productivity',
    description: 'Software per bloccare distrazioni digitali. Supporta digital minimalism e aumenta la produttività.',
    price: 49.99,
    affiliateLink: 'https://example.com/product/22',
    imageUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 15.0,
  },
  {
    id: 23,
    name: 'Corso Investimenti Online',
    category: 'Wealth',
    description: 'Corso completo sugli investimenti per principianti. Video lezioni, materiali e community di supporto.',
    price: 99.99,
    affiliateLink: 'https://example.com/product/23',
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 30.0,
  },
  {
    id: 24,
    name: 'Libro FIRE Movement',
    category: 'Wealth',
    description: 'Guida completa al movimento FIRE. Strategie pratiche per raggiungere l\'indipendenza finanziaria.',
    price: 16.99,
    affiliateLink: 'https://example.com/product/24',
    imageUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 4.5,
  },
  {
    id: 25,
    name: 'Corso Side Hustle',
    category: 'Wealth',
    description: 'Corso step-by-step per creare entrate aggiuntive online. Dalle basi alle strategie avanzate.',
    price: 79.99,
    affiliateLink: 'https://example.com/product/25',
    imageUrl: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 25.0,
  },
  // Benessere Sessuale - Integratori
  {
    id: 26,
    name: 'Integratore Vigore Maschile Premium',
    category: 'Nutrition',
    description: 'Formula completa con L-arginina, zinco, ginseng e maca per supportare energia, performance e vitalità maschile. Ingredienti scientificamente provati.',
    price: 39.99,
    affiliateLink: 'https://example.com/product/26',
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951b55104?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 12.0,
  },
  {
    id: 27,
    name: 'Integratore Libido e Desiderio Femminile',
    category: 'Nutrition',
    description: 'Formula naturale con maca, damiana e ginkgo biloba per supportare il desiderio, l\'energia e il benessere sessuale femminile.',
    price: 34.99,
    affiliateLink: 'https://example.com/product/27',
    imageUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 11.5,
  },
  {
    id: 28,
    name: 'Zinco + Magnesio per Performance Sessuale',
    category: 'Nutrition',
    description: 'Combinazione ottimale di zinco e magnesio per supportare la produzione ormonale, l\'energia e la resistenza. Essenziale per il benessere sessuale.',
    price: 24.99,
    affiliateLink: 'https://example.com/product/28',
    imageUrl: 'https://images.unsplash.com/photo-1574680178050-55c6a6a96e0a?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 8.0,
  },
  {
    id: 29,
    name: 'Maca Peruviana Premium - Energia e Vitalità',
    category: 'Nutrition',
    description: 'Maca peruviana biologica in polvere. Adattogeno naturale che supporta energia, libido e benessere ormonale sia maschile che femminile.',
    price: 29.99,
    affiliateLink: 'https://example.com/product/29',
    imageUrl: 'https://images.unsplash.com/photo-1609859904090-30f4c8462c0c?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 9.5,
  },
  // Corsi e Guide
  {
    id: 30,
    name: 'Corso Completo di Sessuologia Tantrica',
    category: 'Wellbeing',
    description: 'Corso online completo con video lezioni, esercizi pratici e tecniche tantriche per migliorare l\'intimità, la connessione e la soddisfazione sessuale.',
    price: 149.99,
    affiliateLink: 'https://example.com/product/30',
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 35.0,
  },
  {
    id: 31,
    name: 'Guida Pratica: Comunicazione e Intimità di Coppia',
    category: 'Mindset',
    description: 'E-book completo con esercizi pratici per migliorare la comunicazione, l\'intimità e la soddisfazione nella relazione. Tecniche collaudate per coppie.',
    price: 19.99,
    affiliateLink: 'https://example.com/product/31',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 50.0,
  },
  {
    id: 32,
    name: 'Lubrificante Naturale per Benessere Intimo',
    category: 'Wellbeing',
    description: 'Lubrificante naturale a base di ingredienti organici, ipoallergenico e senza parabeni. Perfetto per comfort e benessere intimo.',
    price: 16.99,
    affiliateLink: 'https://example.com/product/32',
    imageUrl: 'https://images.unsplash.com/photo-1556910096-6f5e72db6803?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 10.0,
  },
  {
    id: 33,
    name: 'Integratore Ormonale Femminile Naturale',
    category: 'Nutrition',
    description: 'Formula con fitoestrogeni naturali, vitamina D e calcio per supportare l\'equilibrio ormonale femminile e il benessere intimo.',
    price: 32.99,
    affiliateLink: 'https://example.com/product/33',
    imageUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 9.0,
  },
  {
    id: 34,
    name: 'Set Esercizi Pelvici per Performance Maschile',
    category: 'Fitness',
    description: 'Guida completa con esercizi per rafforzare i muscoli pelvici, migliorare il controllo e aumentare la performance sessuale maschile.',
    price: 27.99,
    affiliateLink: 'https://example.com/product/34',
    imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 15.0,
  },
  {
    id: 35,
    name: 'Corso Online: Comunicazione Sessuale e Intimità',
    category: 'Mindset',
    description: 'Corso video completo per migliorare la comunicazione nella coppia, esprimere desideri e costruire un\'intimità più profonda e soddisfacente.',
    price: 79.99,
    affiliateLink: 'https://example.com/product/35',
    imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 30.0,
  },
  // Sostenibilità Ambientale
  {
    id: 36,
    name: 'Kit Fotovoltaico Domestico 3kW - Energia Solare',
    category: 'Wealth',
    description: 'Kit completo per installazione fotovoltaica domestica da 3kW. Include pannelli solari, inverter, cavi e accessori. Prodotto energia pulita e riduci le bollette elettriche.',
    price: 2999.99,
    affiliateLink: 'https://example.com/product/36',
    imageUrl: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 8.0,
  },
  {
    id: 37,
    name: 'Consulenza Fotovoltaico - Preventivo Gratuito',
    category: 'Wealth',
    description: 'Servizio di consulenza professionale per installazione fotovoltaico. Preventivo gratuito, valutazione incentivi, calcolo risparmio. Supporto completo per la transizione energetica.',
    price: 0.00,
    affiliateLink: 'https://example.com/product/37',
    imageUrl: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 15.0,
  },
  {
    id: 38,
    name: 'Pannelli Solari Portatili - Caricamento USB',
    category: 'Wellbeing',
    description: 'Pannelli solari portatili per ricaricare dispositivi elettronici. Ideali per campeggio, escursioni e emergenze. Energia pulita ovunque tu vada.',
    price: 89.99,
    affiliateLink: 'https://example.com/product/38',
    imageUrl: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 10.0,
  },
  {
    id: 39,
    name: 'Batteria di Accumulo Fotovoltaico - Storage Energia',
    category: 'Wealth',
    description: 'Batteria di accumulo per sistemi fotovoltaici. Immagazzina energia solare per uso notturno. Massimizza l\'autoconsumo e l\'indipendenza energetica.',
    price: 2499.99,
    affiliateLink: 'https://example.com/product/39',
    imageUrl: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 7.5,
  },
  {
    id: 40,
    name: 'Borraccia in Acciaio Inossidabile - Zero Waste',
    category: 'Wellbeing',
    description: 'Borraccia ecologica in acciaio inossidabile, senza BPA. Riduci l\'uso di plastica monouso. Design elegante e duraturo per uno stile di vita sostenibile.',
    price: 24.99,
    affiliateLink: 'https://example.com/product/40',
    imageUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 12.0,
  },
  {
    id: 41,
    name: 'Set Borsa Spesa Riutilizzabile - Zero Plastica',
    category: 'Wellbeing',
    description: 'Set di 5 borse della spesa riutilizzabili in cotone biologico. Elimina la plastica monouso. Durevoli, lavabili e rispettose dell\'ambiente.',
    price: 19.99,
    affiliateLink: 'https://example.com/product/41',
    imageUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 11.0,
  },
  {
    id: 42,
    name: 'Compostiera Domestica - Riciclo Organico',
    category: 'Wellbeing',
    description: 'Compostiera domestica per trasformare rifiuti organici in compost. Riduci i rifiuti e produci fertilizzante naturale per il tuo giardino.',
    price: 79.99,
    affiliateLink: 'https://example.com/product/42',
    imageUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 9.0,
  },
  {
    id: 43,
    name: 'Pompa di Calore Aria-Acqua - Riscaldamento Sostenibile',
    category: 'Wealth',
    description: 'Pompa di calore per riscaldamento e raffrescamento domestico. Alta efficienza energetica, riduce consumi e impatto ambientale. Ideale per case sostenibili.',
    price: 3999.99,
    affiliateLink: 'https://example.com/product/43',
    imageUrl: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 6.5,
  },
  {
    id: 44,
    name: 'Termostato Intelligente WiFi - Risparmio Energetico',
    category: 'Wealth',
    description: 'Termostato smart con controllo WiFi. Programmazione intelligente per ottimizzare consumi e risparmiare energia. Compatibile con Alexa e Google Home.',
    price: 149.99,
    affiliateLink: 'https://example.com/product/44',
    imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 8.5,
  },
  {
    id: 45,
    name: 'Lampadine LED Smart - Illuminazione Efficiente',
    category: 'Wealth',
    description: 'Set di 4 lampadine LED smart dimmerabili, 16 milioni di colori. Consumo ridotto del 80% rispetto alle incandescenti. Controllo via app e assistenti vocali.',
    price: 39.99,
    affiliateLink: 'https://example.com/product/45',
    imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 10.0,
  },
  {
    id: 46,
    name: 'Monitor Consumi Energetici - Smart Energy Meter',
    category: 'Wealth',
    description: 'Dispositivo per monitorare consumi energetici in tempo reale. Identifica sprechi e ottimizza l\'uso dell\'energia. App mobile inclusa.',
    price: 89.99,
    affiliateLink: 'https://example.com/product/46',
    imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 9.5,
  },
  {
    id: 47,
    name: 'Bicicletta Elettrica - Mobilità Sostenibile',
    category: 'Wellbeing',
    description: 'E-bike con batteria removibile, assistenza elettrica fino a 25km/h. Mobilità sostenibile per spostamenti urbani. Riduci emissioni e mantieniti in forma.',
    price: 899.99,
    affiliateLink: 'https://example.com/product/47',
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 5.0,
  },
  {
    id: 48,
    name: 'Corso Online: Stile di Vita Sostenibile',
    category: 'Wellbeing',
    description: 'Corso completo per adottare uno stile di vita sostenibile. Riduzione rifiuti, energia rinnovabile, consumo consapevole. Guida pratica step-by-step.',
    price: 59.99,
    affiliateLink: 'https://example.com/product/48',
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&h=600&fit=crop',
    affiliateProgram: 'Amazon',
    commissionPercentage: 40.0,
  },
];

export function getArticlesByCategory(category: string) {
  return mockArticles.filter(article => 
    article.category.toLowerCase() === category.toLowerCase()
  );
}

export function getArticleBySlug(slug: string) {
  return mockArticles.find(article => article.slug === slug);
}

export function getProductsByCategory(category: string) {
  return mockProducts.filter(product => 
    product.category.toLowerCase() === category.toLowerCase()
  );
}

export function getProductById(id: number) {
  return mockProducts.find(product => product.id === id);
}

export function getRelatedArticles(articleId: number, limit: number = 3) {
  const article = mockArticles.find(a => a.id === articleId);
  if (!article) return [];
  
  return mockArticles
    .filter(a => a.id !== articleId && a.category === article.category)
    .slice(0, limit);
}

export function getArticlesByProductId(productId: number) {
  return mockArticles.filter(article => 
    article.productIds?.includes(productId)
  );
}

